name: opencv_web_example
description: Demonstrates how to use the opencv_web plugin.
publish_to: "none"

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  file_picker: ^5.0.1
  crop_image: ^1.0.2
  opencv_web:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
